name: Go

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.x

# commented out until we actually have tests, and I figure out gocv workflows
#    - name: Test
#      run: go test -v -count=1 -short ./...

    - name: Fmt
      run: go fmt ./...

    - name: Diff
      run: git diff --exit-code .
